name: PWLevel
version: ${project.version}
main: cn.pixelwar.pwlevel.PWLevel
api-version: 1.18
authors: [An_Lan]
depend: [Skript]
commands:
  pwlevel:
    description: PixelWar Level system.
    usage: /<command>
