name: PWItemManager
version: '${project.version}'
main: cn.pixelwar.pwitemmanager.PWItemManager
api-version: 1.18
authors: [ An_Lan ]
depend: [ Skript ]
commands:
  pixelwaritem:
    description: save/get items
    usage: /pixelwaritem
    permission: pw.op